// <auto-generated />
using System;
using AssignmentOne.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssignmentOne.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621194519_SeedVideoGames")]
    partial class SeedVideoGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssignmentOne.Core.Entities.VideoGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            CreateDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An open-world action-adventure game set in Hyrule.",
                            Name = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            CreateDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An epic tale of life in America at the dawn of the modern age.",
                            Name = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            CreateDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A story-driven open world RPG set in a visually stunning fantasy universe.",
                            Name = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            CreateDate = new DateTime(2016, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A challenging action RPG set in a dark, dying world.",
                            Name = "Dark Souls III"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            CreateDate = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A challenging 2D action-adventure set in a beautifully hand-drawn insect kingdom.",
                            Name = "Hollow Knight"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            CreateDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An action RPG set in the Lands Between, created with George R. R. Martin.",
                            Name = "Elden Ring"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            CreateDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kratos and his son Atreus journey through the Norse realms.",
                            Name = "God of War"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            CreateDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An open-world RPG set in the dystopian Night City.",
                            Name = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            CreateDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A roguelike dungeon crawler where you battle out of the Underworld.",
                            Name = "Hades"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            CreateDate = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A shinobi action game set in late 1500s Sengoku Japan.",
                            Name = "Sekiro: Shadows Die Twice"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
